// Autogenerated from Pigeon (v0.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class ACMemoryUsage;
@class ACStartupTime;

@interface ACMemoryUsage : NSObject
@property(nonatomic, strong, nullable) NSNumber * dirtyMemoryUsage;
@property(nonatomic, strong, nullable) NSNumber * ownedSharedMemoryUsage;
@end

@interface ACStartupTime : NSObject
@property(nonatomic, strong, nullable) NSNumber * startupTime;
@end

@protocol ACPollIosStats
-(nullable ACMemoryUsage *)pollMemoryUsage:(FlutterError *_Nullable *_Nonnull)error;
-(nullable ACStartupTime *)pollStartupTime:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ACPollIosStatsSetup(id<FlutterBinaryMessenger> binaryMessenger, id<ACPollIosStats> _Nullable api);

NS_ASSUME_NONNULL_END
